language: python
python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - git clone https://github.com/Micromeda/genome-properties
script:
  - nosetests -v ./
  - ./test_parse_genome_properties_file.py  -i ./genome-properties/flatfiles/genomeProperties.txt
  - ./testing/test_end_to_end.sh
