language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - git clone https://github.com/Micromeda/genome-properties
script:
  - nosetests -v ./
  - ./test_parse_genome_properties_file.py  -i ./pygenprop/testing/test_constants/test_genome_properties.txt
  - ./test_end_to_end.sh
