language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install .
before_script:
  - git clone https://github.com/Micromeda/genome-properties
script:
  - nosetests -v ./
  - ./pygenprop/testing/test_parse_genome_properties_file.py -i ./genome-properties/flatfiles/genomeProperties.txt
  - ./test_end_to_end.sh
