language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - git clone https://github.com/Micromeda/genome-properties
script:
  - nosetests -v ./
  - ./pygenprop/testing/test_parse_genome_properties_file.py -i ./genome-properties/flatfiles/genomeProperties.txt
  - ./pygenprop/testing/test_parse_genome_properties_assignments.py -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.txt -o ./test1.json
  - ./pygenprop/testing/test_parse_interproscan.py -d ./genome-properties/flatfiles/genomeProperties.txt -i pygenprop/testing/test_constants/C_chlorochromatii_CaD3.tsv -o ./test2.json
  - ./pygenprop/testing/test_parse_genome_properties_end_to_end.sh
